export { CaretDown } from './icons/CaretDown'
export { CheckCircle } from './icons/CheckCircle'
export { CloseIcon } from './icons/Close'
export { ErrorCircleIcon } from './icons/ErrorCircle'
export { Eye } from './icons/Eye'
export { EyeSlash } from './icons/EyeSlash'
export { Info } from './icons/Info'
export { MagnifyingGlass } from './icons/MagnifyingGlass'
export { WarningCircle } from './icons/WarningCircle'

export type HiNativeIconName =
  | 'caret-down'
  | 'check-circle'
  | 'close'
  | 'error-circle'
  | 'eye'
  | 'eye-slash'
  | 'info'
  | 'magnifying-glass'
  | 'warning-circle'
