export { CaretDownIcon } from './icons/CaretDown'
export { CheckCircleIcon } from './icons/CheckCircle'
export { CloseIcon } from './icons/Close'
export { ErrorCircleIcon } from './icons/ErrorCircle'
export { EyeIcon } from './icons/Eye'
export { EyeSlashIcon } from './icons/EyeSlash'
export { InfoIcon } from './icons/Info'
export { MagnifyingGlassIcon } from './icons/MagnifyingGlass'
export { WarningCircleIcon } from './icons/WarningCircle'

export type HiIconName =
  | 'caret-down'
  | 'check-circle'
  | 'close'
  | 'error-circle'
  | 'eye'
  | 'eye-slash'
  | 'info'
  | 'magnifying-glass'
  | 'warning-circle'
